apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: svc-auth
  labels: 
    app: svc-auth
spec:
  replicas: 2
  template:
    metadata: 
      labels: 
        app: svc-auth
    spec:
      containers:
      - name: svc-auth
        image: gcr.io/project-tilas/svc-auth:${TAG}
        command:
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: svc-auth-config
            mountPath: /etc/svc-auth/
            readOnly: true
        env:
        - name: SVC_AUTH_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SVC_AUTH_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
        - name: svc-auth-config
          configMap: { name: svc-auth-config } 
---
kind: Service
apiVersion: v1
metadata:
  name: svc-auth
spec:
  selector:
    app: svc-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080